# permissions for end users to edit instrumentedapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instrumentedapplication-editor-role
rules:
- apiGroups:
  - observability.control.plane.keyval.dev
  resources:
  - instrumentedapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - observability.control.plane.keyval.dev
  resources:
  - instrumentedapplications/status
  verbs:
  - get
