# permissions for end users to view collectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: collector-viewer-role
rules:
- apiGroups:
  - observability.control.plane.keyval.dev
  resources:
  - collectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - observability.control.plane.keyval.dev
  resources:
  - collectors/status
  verbs:
  - get
