# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: odigos-lang-detector-role
  namespace: odigos-system
rules:
- apiGroups:
  - "observability.control.plane.keyval.dev"
  resources:
  - instrumentedapplications
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
    - "observability.control.plane.keyval.dev"
  resources:
    - instrumentedapplications/status
  verbs:
    - get
    - patch
    - update